### ISSUE TITLE
Pressing the ESC key closes xviewer

### ISSUE THREAD

**Issue by jbergengh** [linuxmint/xviewer#148]
```
 * Xviewer version 3.0.2
 * Distribution - Mint 20.2
```

**Issue**
I'm not sure if this is a bug or a feature, but pressing the ESC key while viewing a document closes Xviewer.
I'd rather it didn't do this.  I use LibreCAD a lot, which involves frequently having to hit ESC.  I find myself frequently accidentally closing documents I'm also viewing in Xviewer.
If ESC a feature, please consider making it an option in the preferences.
Thanks.

**Steps to reproduce**
Open any document with Xviewer.  Press ESC

**Expected behaviour**
Nothing should happen when pressing ESC

**Comment by programmer-ceds** [comment]
Pressing Esc when in full screen or slide-show mode reverts to not full screen (i.e. the menu etc is shown). Pressing Esc when not in full screen mode closes the program. This is the expected behaviour as defined by the program code. It would be possible to make this configurable via Edit/Preferences but I don't know if there would be support for this - this is the first report about this.

**Comment by jbergengh** [comment]
OK, thank you.  It just catches me by surprise.  I don't think I've ever seen a program that closes by pressing the ESC key before.  I have a work-around that helps somewhat.  I rotate the image then rotate it back.  That way at least I get a warning that I can cancel to avoid getting kicked out.  I can live what that.  Thanks for the quick reply.

**Comment by jbergengh** [comment]
After trying several other image viewers, I was rather surprised to discover that they all can be closed by hitting the ESC key.   I didn't realize this was the case.  ESC is a feature, not a bug.  I think we can close this issue.  Thanks again.
