### ISSUE TITLE
[Feature Request] Compare Mode

### ISSUE THREAD

**Issue by GalacticCake** [linuxmint/xviewer#156]
Xviewer 3.0.2
Linux Mint Cinnamon  

Would it be possible to incorporate a feature that would let you compare multiple images side by side, in a single window. So if I were to choose multiple images, then I can compare them side by side, in a single window. I'm not talking about the Slideshow mode, for that you are required to use your arrows keys to move to the next slide. I'm currently editing an image, I'm trying to compare the before and after result. I would prefer if the image wasn't in Slideshow mode, but instead side by side. 

I could install another software which includes this feature by default, but then I would have multiple Image Viewers on my computer. Instead of keeping multiple Image Viewers, perhaps this software could include this feature? I apologize for suggesting this idea here, I'm not sure where to send suggestions.

**Comment by programmer-ceds** [comment]
You could just run two instances of xviewer not maximised side by side. Given that there aren't big sidebars (if you don't have the side pane enabled) what you get is probably as good as you would get from the feature that you suggest. Whilst perhaps a bit more clunky it is available now.

**Comment by GalacticCake** [comment]
I'm not sure how to even open another instance of Xviewer. If I press the Superkey then search for Xviewer and select it, then another instance does not open. If I right click on the Xviewer icon, located on the bottom of my screen, there is no option to open a new window. Even if I tried to run Xviewer through the terminal, it doesn't work for me. 

Regardless, opening multiple instances of Xviewer results in more resoruces to be used, even though it is by a small amount. Anyway what your saying requires me to split my screen, which requires more effort. What if someone wanted to compare 4 images? He would have to split his screen four times. There might be people who do this often, so after some time it becomes tedious. It might be a more ideal idea to incorporate this feature which lets you compare images side by side, in the same window.

**Comment by programmer-ceds** [comment]
Browse to the first image in your file manager and open it - double-click if xviewer is the default image viewer, "Open With" otherwise. Open a second image in the same way using your file manager and you will get a second instance of xviewer running (as evidenced by the small '2' over the xviewer icon in the taskbar). If you un-maximise both instances of xviewer you can drag their windows around and resize them to suit so that you have the two images side by side or one above the other.

I don't think that in this day and age the effect on resources would be significant and you don't have to 'split' your screen.

Your alternative is to find an application that does this already as, given the amount of work involved, I think that it is unlikely to be implemented in xviewer (that is my personal opinion - I'm not an xviewer developer and don't claim to speak for them).
