### ISSUE TITLE
Read image from stdin

### ISSUE THREAD

**Issue by GoodClover** [linuxmint/xviewer#175]
```
 * Xviewer 3.2.4
 * Mint 20.3 (Una)
```

Being able to read an image from stdin rather than a file would be useful, I have a variety of script that output images in [PPMs](<https://en.wikipedia.org/wiki/Netpbm>) (which xviewer supports), and would like to avoid having to write them to a file before viewing.

I've tried using the normal `-` as a filename to request stdin be used, but it appears xviewer does not do this.

**Comment by clefebvre** [comment]
Although it would be an interesting feature, we're not planning to implement it. I don't think it's something many people would use. It would also impact the design of xviewer, since many of the features rely on the presence of a path.

An alternative viewer could be used for this use case, or a python wrapper using tempfile maybe?
