### ISSUE TITLE
After using "Copy" function from the Menu, pasting is not possible

### ISSUE THREAD

**Issue by spamegg1** [linuxmint/xviewer#190]
```
 * Xviewer version 3.4.1
 * Distribution - Mint 21.2
```

**Issue**
After "copy" is used, pasting is not possible.

**Steps to reproduce**
1. Open an image.
2. Go to `Edit / Copy` and click. (Or press `Ctrl+C`)
3. Open a file manager (such as Nemo).
4. Right-click to see "Paste" option greyed out. (Or try `Ctrl+V` and it does nothing.)

**Expected behaviour**
Pasting should work after copying.

**Other information**
Video:
[output.webm](https://github.com/linuxmint/xviewer/assets/4255997/0f25da97-7b8f-4417-8a7e-6acb33f9c70f)

**Comment by programmer-ceds** [comment]
Not sure what you are expecting to happen when you paste an image (rather than an image file) into a file browser such as nemo. Having used Edit/Copy in xviewer when displaying an image I can paste it into GIMP, Drawing, Inkscape etc. Similarly if I copy an image from GIMP using Edit/Copy I can't paste it into nemo.
