### ISSUE TITLE
Feature: Is it possible to have a RPM installer ?

### ISSUE THREAD

**Issue by harmin-parra** [linuxmint/xviewer#196]
```
 * Xviewer version (xviewer --version) 3.4.4
```

**Issue**
Is it possible to have an RPM installer ?

And not just for `xviewer`, but in general, for other linuxmint related software ? (like `pix`, etc)

**Other information**
It would be nice to be able to install the complete suite of applications related to Cinnamon (`xviewer`, `pix`, `bulky`, `mintstick`, 
`timeshift`, `warpinator`, `mintbackup`, etc) in an RPM system like Fedora.

**Comment by leigh123linux** [comment]
It makes no sense to have mintstick or mintbackup in fedora, timeshift is available in fedora repo.
As for the other xapps, they were dropped from fedora due to workload after the other maintainer left.
This hasn't changed, someone else will need to get reviewed and maintain them at fedora.

https://src.fedoraproject.org/rpms/xviewer/commits/rawhide
