### ISSUE TITLE
The "Save" action when closing Xviewer is duplicating actions

### ISSUE THREAD

**Issue by dharple** [linuxmint/xviewer#30]
Reproduction steps:

1) In Nemo, select a folder with multiple images.
2) Double click on one to open it in Xviewer.
3) Rotate the image (clockwise or counterclockwise, it doesn't seem to matter) 90 degrees.
4) Press the left arrow button to go to the next image.
5) Press Control-W to quit.
6) You'll be presented with a "Save" dialog, warning you that the changes you just made will be lost.
7) Click Save.
8) Wait a moment for the thumbnail to regenerate.
9) Click on the image.  The action that you selected has been applied twice, and the image is now rotated 180 degrees.

I'm using Xviewer 1.2.2 under Linux Mint 18.1, with Cinnamon 3.2.7.  I'm happy to provide additional details or screenshots if needed.

**Comment by jmssil** [comment]
I think I also got this bug. The images were rotated once and then saved. When I reopened them, they were upside-down. Not sure if the commands are applied **twice** as Doug says because the 2nd time I rotated them 2x (to correct the fact they were upside-down) and when I reopened they were still upside-down.

**Comment by programmer-ceds** [comment]
I can't reproduce this in xviewer 2.6.2 on Linux Mint 20. Following the steps exactly gives the correct result not as noted above.

**Comment by dharple** [comment]
OK!  Thanks.  It's probably safe to assume that this issue was fixed at some point along the way.
