### ISSUE TITLE
Portrait Photos shown in landscape

### ISSUE THREAD

**Issue by Machion** [linuxmint/xviewer#94]
```
 * Xviewer version (xviewer --version)
2.4.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Manjaro 19.0.2/Cinnamon 4.4.8
```

**Issue**
When I open a portrait photo (made with my motox4) it is shown in landscape (turned 90° to left). The image file is jpeg and with other image viewers (pix or gthumb) it's ok. 
If my memory is correct, many versions ago, it was no issue.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by programmer-ceds** [comment]
Obvious question - is xviewer "Edit/Preferences/Automatic Orientation" selected?

**Comment by Machion** [comment]
Yes it's selected. When it's off there is no difference.
The thumbnail preview of nemo shows the photo correct too.
5. April 2020 11:50, "programmer-ceds" <notifications@github.com (mailto:notifications@github.com?to=%22programmer-ceds%22%20<notifications@github.com>)> schrieb:
	Obvious question - is xviewer "Edit/Preferences/Automatic Orientation" selected?

**Comment by programmer-ceds** [comment]
Possible reasons (there may be others):

1. The image may have its orientation tag set to show that orientation is not required
2. The orientation tag is set to an illegal value
3. The orientation tag has been deleted
4. The orientation tag is not being handled correctly by xviewer (I see this as the least likely option)

All of the possibilities listed apply just to the orientation tag for the main image - from what you say the orientation tag for the thumbnail is correct.

Has the file been edited or is it straight out of the camera?

If you have exiftool installed then the following command will show the setting of the orientation tag for the main image:
    exiftool "file.jpg"

If you are able to use a binary hex editor I could supply you with details on how to find, inspect and change the orientation tags (for the main image and the thumbnail). If you can't do this can you provide a copy of the file? I don't know if you can attach files like that to this thread or whether you would have to post a link to the file on Google Drive or similar.

If the problem is due to the actions of an image editor it would be possible to edit the orientation tags for the main images whilst leaving the tags for the thumbnails unchanged. I have a Windows based program, EXIF Rotate, that would do this. I have recently ported this to run under Linux. The program will batch rotate images by altering the EXIF orientation tags but in this mode it alters both thumbnail and main image. When used on individual files it offers the option of only changing the main image or the thumbnail orientation (or both). This is a GUI program (and I'm sure that there are others available).

The first thing is to try to determine where the problem lies by inspecting the image file (and I suspect that the problem lies with the file rather than xviewer)

**Comment by programmer-ceds** [comment]
@Machion Did you get anywhere looking at the files that don't get orientated by xviewer? If not could you post one of the problem files and I will look at it.

**Comment by Machion** [comment]
Sorry for the delay. I was busy. I think it's faster, when I attach a photo. 
Interesting that github also rotates the photo (as I see in the preview), but as I mentioned before no other program on my pc rotates it.

![IMG_20200414_174700282](https://user-images.githubusercontent.com/43423878/79246550-9f7af700-7e79-11ea-9a42-98dbbb2c7dc9.jpg)

**Comment by programmer-ceds** [comment]
I have right-clicked on the image and saved it to my desktop. When I open it with xviewer it is shown in portrait mode with the writing horizontal and the normal way up. I'm also using 2.4.3. If I enable gallery view, which I assume displays thumbnails, the image is again shown in portrait mode - the question is why its shown on its side above. Could you put the image on Google Drive and post a link - that way there are fewer steps involved.

**Comment by programmer-ceds** [comment]
Just checked that the image appears in landscape format if I disable Automatic orientation (although it shows the size of the image as 3024x4032 whereas it should be 4032x3024 - this is corrected if the rotate buttons are used).

Looking at the jpg itself, in the version that I saved to my desktop both orientation tags (thumbnail and main image) appear to be set to 6 - which is rotate clockwise 90 degrees. So the file as I have it is behaving exactly as I would expect. I suppose there is a chance that something in the Firefox save process has corrected the orientation tags - taken the thumbnail tag for both of them - but this seems unlikely. Still begs the question as to why it is displayed in landscape mode on this site.

**Comment by programmer-ceds** [comment]
Answering my own question - the image is displayed, for me anyway, in landscape mode as Firefox doesn't automatically orientate the image. If I understand correctly what you said above your browser does handle the orientation.

I have posted a copy of your file that displays in portrait mode when opened in xviewer (this is simply a renamed copy of the file that I downloaded - I haven't altered it in any (deliberate) way). What happens if you open this file with your version of xviewer?

https://drive.google.com/open?id=1ckIMmJz_RLsvTwIByYfZSh3EkNJBBYxx

If that opens correctly but your original version doesn't a comparison of the two files would be in order.

If this file also comes up in landscape mode there is presumably some difference in the versions of xviewer that we are using. Where did you get V2.4.3 from? I am using the version built from the latest master plus the changes from the key 1 behaviour branch of my fork but I can't see anything in the change log that relates to the problem.

**Comment by Machion** [comment]
Thanks for your testing/research! 
Now I'm on v2.6.0 - same behavior. I have it from the Manjaro repo.

I followed your google-drive link. The preview in browser is correct. When I download it, the preview in nemo 4.6.2 is correct, but in xviewer still landscape. 

When I open it in gThumb (which shows it correct) I can read the exif-metadata. It says orientation: right-top

I attach the foto again zipped. Maybe it preserves metadata better, but it seems the metadata of the foto from your drive are still correct.

[IMG_20200414_174700282.jpg.zip](https://github.com/linuxmint/xviewer/files/4750264/IMG_20200414_174700282.jpg.zip)

**Comment by Machion** [comment]
There is only the General tab. 
I will first ask Oberon from Manjaro Team. He maintains the package.

**Comment by oberon-manjaro** [comment]
Thank you @Machion , I just had a look at our package.
exif support was not explicitly disabled, but the **libexif** dependency was missing.
Should be fixed in **pkgrel 2**, now in the repos.

**Comment by programmer-ceds** [comment]
Good to get that sorted. Another issue that can be closed now.

**Comment by Machion** [comment]
Thanks to all!
